### ISSUE TITLE
Certain images are not loaded

### ISSUE THREAD

**Issue by Cnidarias** [Anarbb/LibreRecipes#2]
When randomly checking through different pages on the home page there seem to be some issues with redirects:

![image](https://user-images.githubusercontent.com/5615502/112989407-2f867f00-9165-11eb-9bbe-2e8022b06dd9.png)

Here you seem to have some issues with redirects (likely not caused by you) 

Additional note - I think you should at least provide a link to where the recipes come from?

**Comment by Anarbb** [comment]
This will be fixed, if you host images on your own CDN, I am aware of the problem, and it's usually either an HTTPS request problem or the image redirects to the website (probably embedding protection) 
I will work on it, maybe change the URLs for the time being
