### ISSUE TITLE
App start shouldn't have debug on production

### ISSUE THREAD

**Issue by JoseDeFreitas** [Anarbb/LibreRecipes#5]
Hi. You should remove that `debug=True` from the app call because the app is in production. Refer to [this document](https://flask.palletsprojects.com/en/1.1.x/errorhandling/#debugging-application-errors) from the Flask documentation.
https://github.com/Anarbb/LibreRecipes/blob/0c07878d154011e593d1351f849ceca87a2032d4/main.py#L5

**Comment by Anarbb** [comment]
fixed, thank you
